/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */
int i = 0;

public void changeoventemp(GKnob source, GEvent event) { //_CODE_:Temp:491161:
  println("Temp - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:Temp:491161:

public void changetimeforoven(GKnob source, GEvent event) { //_CODE_:time:476537:
  println("time - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:time:476537:

synchronized public void Receipe_Window(PApplet appc, GWinData data) { //_CODE_:Receipe:431125:
  appc.background(230);
} //_CODE_:Receipe:431125:

synchronized public void Music_Window(PApplet appc, GWinData data) { //_CODE_:Music:895587:
  appc.background(230);
} //_CODE_:Music:895587:
ArrayList<String> ingredients_selected = new ArrayList<String>();
public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:693695:
  if (ingredients_selected.contains(source.getSelectedText())){
    println("ingredient already selected");
  }
  ingredients_selected.clear();
  for( int j = 0; j <= i; j++){
    ingredients_selected.add(dropLists.get(j).getSelectedText());
  }
  println(ingredients_selected);
  println("dropList1 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:dropList1:693695:
ArrayList<Float> quantities_values = new ArrayList<Float>();
public void change_quantities(GCustomSlider source, GEvent event){
  quantities_values.clear();
  for( int j = 0; j <= i; j++){
    quantities_values.add(ingredient_quantities.get(j).getValueF());
  }
  println(quantities_values);
}
public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:254614:
  i++;
  dropLists.add(new GDropList(Receipe, 29, 60+ 40*i, 90, 80, 3, 10));
  dropLists.get(i).setItems(loadStrings("list_374668"), 0);
  dropLists.get(i).addEventHandler(this, "dropList1_click1");
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
  
  ingredient_quantities.add(new GCustomSlider(Receipe, 120, 60 + 40*i, 100, 40, "grey_blue"));
  ingredient_quantities.get(i).setLimits(50.0, 10.0, 100.0);
  ingredient_quantities.get(i).setNumberFormat(G4P.DECIMAL, 2);
  ingredient_quantities.get(i).setOpaque(false);
  ingredient_quantities.get(i).addEventHandler(this, "change_quantities");
} //_CODE_:button1:254614:
public void generating_receipes(GButton source, GEvent event){
  cooking_mode = true;
}
public void play_music(GButton source, GEvent event){
  Song.play();
}
public void pause_music(GButton source, GEvent event){
  Song.pause();
}
public void change_volume(GCustomSlider source, GEvent event){
  Song.amp(source.getValueF());
}
// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Main window");
  Receipe = GWindow.getWindow(this, "Receipe", 800, 200, 800, 400, JAVA2D);
  Receipe.noLoop();
  Receipe.setActionOnClose(G4P.KEEP_OPEN);
  Receipe.addDrawHandler(this, "Receipe_Window");
  dropLists.add(new GDropList(Receipe, 29, 60, 90, 80, 3, 10));
  dropLists.get(0).setItems(loadStrings("list_374668"), 0);
  dropLists.get(0).addEventHandler(this, "dropList1_click1");
  button1 = new GButton(Receipe, 190, 145, 80, 30);
  button1.setText("add ingerdient");
  button1.addEventHandler(this, "button1_click1");
  generate_receipes = new GButton(Receipe, 500, 300, 80, 30);
  generate_receipes.setText("generate receipes");
  generate_receipes.addEventHandler(this, "generating_receipes");
  ingredient_quantities.add(new GCustomSlider(Receipe, 120, 60, 100, 40, "grey_blue"));
  ingredient_quantities.get(0).setLimits(50.0, 10.0, 100.0);
  ingredient_quantities.get(0).setNumberFormat(G4P.DECIMAL, 2);
  ingredient_quantities.get(0).setOpaque(false);
  ingredient_quantities.get(0).addEventHandler(this, "change_quantities");
  Music = GWindow.getWindow(this, "Music", 0, 200, 800, 400, JAVA2D);
  Music.noLoop();
  Music.setActionOnClose(G4P.KEEP_OPEN);
  Music.addDrawHandler(this, "Music_Window");
  play_button_music = new GButton(Music, 0, 0, 80, 30);
  play_button_music.setText("play");
  play_button_music.addEventHandler(this, "play_music");
  pause_button_music = new GButton(Music, 100, 0, 80, 30);
  pause_button_music.setText("pause");
  pause_button_music.addEventHandler(this, "pause_music");
  volume = new GCustomSlider(Music, 0, 60, 80, 30);
  volume.setLimits(0.5, 0.0, 1.0);
  volume.setNumberFormat(G4P.DECIMAL, 2);
  volume.setOpaque(false);
  volume.addEventHandler(this,"change_volume");
  
  Receipe.loop();
  Music.loop();
}

// Variable declarations 
// autogenerated do not edit
GKnob Temp; 
GButton play_button_music;
GButton pause_button_music;
GCustomSlider volume;
GLabel ovenstemp; 
GKnob time; 
GLabel timelabel; 
GWindow Receipe;
ArrayList<GDropList> dropLists = new ArrayList<GDropList>();
ArrayList<GCustomSlider> ingredient_quantities = new ArrayList<GCustomSlider>();
GCustomSlider oventemp; 
GLabel Ovenslabel; 
GWindow Music;
GButton button1;
GButton generate_receipes;
