/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:Receipe:963868:
  appc.background(230);
} //_CODE_:Receipe:963868:

synchronized public void win_draw2(PApplet appc, GWinData data) { //_CODE_:Music_Player:337772:
  appc.background(230);
} //_CODE_:Music_Player:337772:

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:home:836260:
  appc.background(230);
} //_CODE_:home:836260:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){

  home = GWindow.getWindow(this, "homescreen", 0, 0, 500, 500, JAVA2D);
  home.noLoop();
  home.setActionOnClose(G4P.KEEP_OPEN);
  home.addDrawHandler(this, "win_draw3");
  home.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow Receipe;
GWindow Music_Player;
GWindow home;
